global:
  message: Welcome to customer service prod environment!!
server:
  port: 8082
message: Hello from prod!!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_prod
    username: root
    password: hammad@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
